remove backticks in NativeDOM.cpp (#57573)
Summary:
MSVC is highly allergic to backticks in #pragma and will panic with error C2018: unknown character '0x60'

I'm currently preparing my React Native for Unreal Engine OOT platform, and as part of that I'm compiling with MSVC. MSVC doesn't tolerate the backticks here.

## Changelog:

[GENERAL] [FIXED] - fixed MSVC compilation of NativeDOM.cpp by removing backticks

Pull Request resolved: https://github.com/react/react-native/pull/57573

Test Plan: Check that MSVC no longer complains about backticks

Reviewed By: cortinico

Differential Revision: D112348262

Pulled By: christophpurrer

fbshipit-source-id: 060c357b2f1a642129e56226fa7125622ed0d99e